### ISSUE TITLE
Use of Icons insteads of names for tabs

### ISSUE THREAD

**Issue by CaffeineOnIce** [TJYSunset/Phocid#10]
Disabling scrollable tabs causes the names to go into ellipsis. Please change the tab names into icons instead. 
![Screenshot_20241202_163822_Phocid](https://github.com/user-attachments/assets/1a2df27a-9a30-4155-b7a6-a276df74513c)

and a small question. Why is deleting songs intentionally left out? It's a pretty good feature though?

**Comment by TJYSunset** [comment]
I'll take a look at this later.

> Why is deleting songs intentionally left out?

Primarily because working with files on Android nowadays is torture. Deleting files also requires asking for an extra permission, which is another kind of torture.

Also there's a whole dedicated category of apps called file managers for this task.

**Comment by TJYSunset** [comment]
Added in 8cc7b12be57ea319966ea35948fb1de304249980
