### ISSUE TITLE
Titles showing as "<unknown>" on some songs

### ISSUE THREAD

**Issue by ahmark-new** [TJYSunset/Phocid#15]
As the app scanned my songs. Many songs were listed as "<unknown>", Although, they work but the title is <unknown>
![Screenshot_2024-12-06-22-53-09-538_org sunsetware phocid](https://github.com/user-attachments/assets/376c680b-ab82-49a4-86e6-7c37398d1768)

**Comment by TJYSunset** [comment]
Have you tried enabling (or disabling) "Advanced metadata extraction" in preferences?

**Comment by ahmark-new** [comment]
I cant find any option like "Advanced metadata extraction"  in preferences.

**Comment by TJYSunset** [comment]
Please get the latest release on GitHub:
https://github.com/TJYSunset/Phocid/releases/latest

F-Droid is very slow at publishing new upgrades.

---

But enabling "Advanced metadata extraction" should produce an identical result to your version. Can you provide a sample file that displayed as "<unknown>" inside the app so I can investigate?

**Comment by ahmark-new** [comment]
It was fixed just by updating to the latest version. Thankyou for your
assistance.

**Comment by TJYSunset** [comment]
Can you still provide a sample file? If not, what type of file are those (e.g. MP3s)? This can help fixing the "advanced metadata extraction" feature for those who need it. Thanks in advance.

**Comment by ahmark-new** [comment]
When I turned on 'metadata extraction' and rescanned, the same problem
occurred. However, turning it off and rescanning fixed the issue. I've
attached one of the affected audio files(MP3).

**Comment by TJYSunset** [comment]
Email attachments doesn't seem to work on GitHub. Can you upload a file via GitHub's web interface?

**Comment by ahmark-new** [comment]
[MP3 File.zip](https://github.com/user-attachments/files/18047695/MP3.File.zip)

GitHub doesn't seem to accept direct MP3 files, so I compressed it into a ZIP file.

**Comment by TJYSunset** [comment]
Fixed in a4feb318ab749f6b9a853ce6780f960ce6ee5463
