### ISSUE TITLE
Shuffle feature

### ISSUE THREAD

**Issue by Sahitk1** [TJYSunset/Phocid#18]
Love this app! The simple and easy to use UI is excellent, But unless I am missing something there is no Shuffle feature? I like to not know which song will come next while I'm doing a activity so can you please add it. Thanks!!

**Comment by TJYSunset** [comment]
![Screenshot](https://github.com/user-attachments/assets/ef68af0c-240e-4aa7-b5d3-4b5f504c7ac9)

Is this what you are looking for?

**Comment by Sahitk1** [comment]
> ![Screenshot](https://private-user-images.githubusercontent.com/12986688/393585488-ef68af0c-240e-4aa7-b5d3-4b5f504c7ac9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM2NTI4MTUsIm5iZiI6MTczMzY1MjUxNSwicGF0aCI6Ii8xMjk4NjY4OC8zOTM1ODU0ODgtZWY2OGFmMGMtMjQwZS00YWE3LWI1ZDMtNGI1ZjUwNGM3YWM5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA4VDEwMDgzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkzM2YyY2I3NzhhMTgyMTFmYTU3MDQzNmEwOGU2NDI3NTgzYWQ4YjU3MWVmMmE1NDAxMTViNjRjYTE2NGM1NTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.kgNSvsyBjIGfWqW5rV5Yfo3YVAuL-aQJMVWdL4IiC3g)
> 
> Is this what you are looking for?

Yes , thank you I'm dumb AF I never clicked on the track I only viewed them from the grid
