### ISSUE TITLE
Scanning issue

### ISSUE THREAD

**Issue by Lucky390163** [TJYSunset/Phocid#2]
1) Taking too much time to scan even isn't showing progress.So, can you add a progress shower?

2) The app is crashing every time.Seems are not optimized for bigger libraries

3) Too laggy on scrolling.Otherwise a good app.

**Comment by Lucky390163** [comment]
![Screenshot_20241201_102009_Files](https://github.com/user-attachments/assets/66fb5c11-c2b3-4e57-9206-32bb45255cce)
Nothing found 
Android 13

**Comment by Lucky390163** [comment]
Bro app is scanning music every time, which is a very long process.Seems quite annoying
![Uploading Screenshot_20241201_102209_Phocid.jpg…]()

**Comment by TJYSunset** [comment]
Can't say for certain, but looks like the app ran out of memory (so it didn't even get a chance to save a crash log). I'll investigate in ways to reduce memory usage.

**Comment by TJYSunset** [comment]
I just profiled memory usage on my phone, and it's only (?) using 500MB of memory. Does your phone have at least 1 GB of free RAM? (Asking this to ensure the cause is memory problems)

**Comment by Lucky390163** [comment]
Why device has 4 gb of free ram.

Apps like poweramp and musicolet have no issues

**Comment by Lucky390163** [comment]
My other music players are baeed on SAF framework by Google

**Comment by TJYSunset** [comment]
Does this build solve indexing problems and crashes? (**DO NOT** enable "advanced metadata extraction" in preferences, that's the culprit)

[app-release.zip](https://github.com/user-attachments/files/17968008/app-release.zip)

> Too laggy on scrolling

Ironically this is caused by the scrollbar. I'll fix it together with #3.

**Comment by Lucky390163** [comment]
No its same

**Comment by TJYSunset** [comment]
[app-release.zip](https://github.com/user-attachments/files/17968102/app-release.zip)

This build doesn't solve anything, but it adds a progress indicator. Are you seeing ~3000 total tracks in the indicator? And what's the exact speed of the scan?

**Comment by Lucky390163** [comment]
It doesn't show anything scanning library no progress.
 I don't know speed.

**Comment by TJYSunset** [comment]
Have you installed the apks from the zips in the comment?
The second apk should have a SHA256 of `9472d0b019652614f5284646211687879912c52a7d7f261e84f4418f352eeefe`

**Comment by Lucky390163** [comment]
Yes, and when i cleared cache it started scanning again with no songs can you take a look

**Comment by TJYSunset** [comment]
Scan result is saved as application cache, if you clear cache it **WILL** scan again.

Did you just install the correct APKs (and the previous claims of the fixes not working are based off miscommunication)? Does the fix work for you now?

**Comment by Lucky390163** [comment]
Yrs but you can fix cac issue it will improve the app a lot

**Comment by TJYSunset** [comment]
What cache issue? Is your system somehow automatically clearing cache very frequently?

**Comment by Lucky390163** [comment]
When i clear cache everytime it starts scanning process again and again.It shows no tracks found

**Comment by TJYSunset** [comment]
Why are you clearing cache? Are you using some batch cache clearing app to save space?

**Comment by Lucky390163** [comment]
Yes as i have only 1 gb left on device storage.

**Comment by Lucky390163** [comment]
Yes so please can you change this like other foss apps Grampophone loads library in 0.5 secs and even i clean cache it won't reset.

Humble request to improve the app

**Comment by TJYSunset** [comment]
I can't publish a new version right now due to Bugs by Google™ (I can't even reliably compile the project, WTF), so here's a temporary build in case you need it:
[https://github.com/user-attachments/files/17969494/app-release.zip](https://github.com/user-attachments/files/17969494/app-release.zip)

<details>
<summary>backup, you don't need this</summary>

[mapping.zip](https://github.com/user-attachments/files/17969496/mapping.zip)

</details>

**Comment by secretmango** [comment]
For me the scanning took forever too. Stopping and reopening the app, suddenly everything was there.

**Comment by Lucky390163** [comment]
Hope you will fix it soon..

**Comment by TJYSunset** [comment]
Fixes published in [v20241201](https://github.com/TJYSunset/Phocid/releases/tag/v20241201)

**Comment by Lucky390163** [comment]
I know.
