### ISSUE TITLE
Sorting by last added

### ISSUE THREAD

**Issue by rufatagayev** [TJYSunset/Phocid#21]
Can you please add sorting tracks by last added please? It should be available from the media library, as almost all similar music players support this feature.

Many thanks!

**Comment by TJYSunset** [comment]
Do you mean filesystem modification date or newly scanned as in #9? The former is trivial to implement, while the latter is unreliable and I personally dislike the idea.

**Comment by rufatagayev** [comment]
I'm talking about this: https://developer.android.com/reference/android/provider/MediaStore.MediaColumns#DATE_ADDED

I haven't done a music app yet, but I know most media apps sort tracks by date added and use a standardized approach, which seems to be the above.

**Comment by TJYSunset** [comment]
Missed that one in the docs. Thanks for pointing it out.

Will take a look tomorrow (it's 22:30 here.)

**Comment by TJYSunset** [comment]
Added in 4acea807771e33ddde80362629b84563d29eefba.
