### ISSUE TITLE
Adding a song to "play next" restarts the current queue

### ISSUE THREAD

**Issue by spacebot3000** [TJYSunset/Phocid#23]
This is really good!! There's just one thing keeping me from using it: when using the "play next" action on a song, it does add that song to the queue after the current song, but it also restarts the queue from the first song. Tested on a Pixel 8 on Android 15. I'm also seeing the choppy animations that others have reported.

**Comment by spacebot3000** [comment]
Thanks! Regarding animation: I actually am on the latest version, but after uninstalling and reinstalling, the animation issue has subsided. Seems like it was an issue on my end.

**Comment by TJYSunset** [comment]
Fixed in 1e73004634675c85d17b45636209fc177341b20c. You can download the latest version again to get the fix.

**Comment by TJYSunset** [comment]
Fixed in b5ef519c9f73389cbe656e7c37cbbe9d6dfa27f8. Please get the latest version again to get the fix.
