### ISSUE TITLE
Changing queue order

### ISSUE THREAD

**Issue by CaffeineOnIce** [TJYSunset/Phocid#25]
Is it possible to add a feature to change the queue order like this? 

https://github.com/user-attachments/assets/dacfb05c-91dd-471c-af2c-c6992beb9378

**Comment by TJYSunset** [comment]
Added in 0990cb883000234017e998acc3eddcf471e6da96

Will glitch out if you mess with it too much, in that case just close the now playing screen to reset. I have no interest in investigating why or fixing it, because I spent 10 hours dealing with supernatural bugs just to make it work.
