### ISSUE TITLE
[Feature request] Music directories

### ISSUE THREAD

**Issue by van-de-bugger** [TJYSunset/Phocid#27]
It seems that Phocid scans the entire storage for audio files. This is not always right thing to do: I have a large library of audiobooks on my smartphone, and Phocid detects these audiobooks and adds them to the music library. However, a good music player is not necessarily a good audiobook player: the requirements for playing music and audiobooks are too different.

So, I would like Phocid to ignore audiobooks. The easiest way, I think, is to have a setting in Phocid — a list of directories with music (or, alternatively, a list of directories that Phocid should ignore).

**Comment by TJYSunset** [comment]
There's a blacklist feature in preferences. Just add a rule `/your audiobook folder name here/`.

**Comment by van-de-bugger** [comment]
Could you please document relationship between block and allow lists? How Phocid makes a desicion? If I add `/Music/` to the allow list, will Phocid looks for the music only in this directory?

**Comment by TJYSunset** [comment]
There's literally a help button down the list...

!["Indexing help"](https://github.com/user-attachments/assets/62b112b9-83a7-439b-9532-7045b4f60def)

**Comment by van-de-bugger** [comment]
Oh, thanks.
