### ISSUE TITLE
Artist names containing non-Latin-1 characters are not always displayed correctly

### ISSUE THREAD

**Issue by l3u** [TJYSunset/Phocid#29]
Hi all :-)

Using 20241212 installed via F-Droid, I see problems with artist names containing non-Latin-1 characters.

Example: I have an album from "Sašo Avsenik und seine Oberkrainer". When I search for "Avsenik" in "Artists", I get two distinct matches (it's only one album), one with the real "š" character, and one with the unicode character displayed as a wrong encoding:
![Screenshot_20241219-215550](https://github.com/user-attachments/assets/b0e875a5-914f-4041-b851-130bee501cf9)
I can choose both artist versions and see the assigned songs. Interestingly, for the version displayed incorrectly, all song titles are ASCII-only:
![Screenshot_20241219-215558](https://github.com/user-attachments/assets/7d7349d2-fccc-4725-b201-6e4f50ee0d69)
whereas the correct version exclusively contains song with non-ASCII characters:
![Screenshot_20241219-215613](https://github.com/user-attachments/assets/b4d4873d-0480-47d8-8d62-dd1bb85edd6b)

When you open an UTF-8 text file containing "Sašo" using ISO-8859-1, you get "SaÅ¡o", so I think you use ISO-8859-1 here instead of UTF-8.

All files are Opus files tagged via MusicBrainz. So the metadata is consistent across all. Here's the opusinfo output for two of the "different artist" files:

    $ opusinfo "02. Wann kommst du zu mir.opus"
    Processing file "02. Wann kommst du zu mir.opus"...

    New logical stream (#1, serial: 29e0da3a): type opus
    Encoded with libopus 1.4, libopusenc 0.2.1
    User comments section follows...
            ...
            ALBUM=Polkaklang ein Leben lang!
            ALBUMARTIST=Sašo Avsenik und seine Oberkrainer
            ALBUMARTISTSORT=Avsenik, Sašo und seine Oberkrainer
            ARTIST=Sašo Avsenik und seine Oberkrainer
            ARTISTS=Sašo Avsenik und seine Oberkrainer
            ARTISTSORT=Avsenik, Sašo und seine Oberkrainer
            ...
            TITLE=Wann kommst du zu mir
            ...

and

    $ opusinfo "07. Wenn Mädchen träumen.opus"
    Processing file "07. Wenn Mädchen träumen.opus"...

    New logical stream (#1, serial: 27b1e98e): type opus
    Encoded with libopus 1.4, libopusenc 0.2.1
    User comments section follows...
            ...
            ALBUM=Polkaklang ein Leben lang!
            ALBUMARTIST=Sašo Avsenik und seine Oberkrainer
            ALBUMARTISTSORT=Avsenik, Sašo und seine Oberkrainer
            ARTIST=Sašo Avsenik und seine Oberkrainer
            ARTISTS=Sašo Avsenik und seine Oberkrainer
            ARTISTSORT=Avsenik, Sašo und seine Oberkrainer
            ...
            TITLE=Wenn Mädchen träumen
            ...

My wild guess would be that it's not assumed that the vorbiscomment content is UTF-8 encoded (the tag values are always UTF-8, cf. the Opus documentation and/or the Ogg Vorbis documentation).

It seems like the program tries to guess the encoding, based on the song title: "Wann kommst du zu mir" is pure ASCII. Here, the "š" in the artist's name is letter salad. In contrast, "Wenn Mädchen träumen" contains the non-ASCII "ä" character, and here, we get the "š" correctly. As said, all songs for the correctly parsed artist version contain non-ASCII characters, whereas all with the wrong encoding artist are pure ASCII.

Just guesswork though ;-)

**Comment by TJYSunset** [comment]
Have you tried "Advanced metadata extraction" in preferences?

**Comment by l3u** [comment]
Woah, that was fast :-D

Activating this option actually fixes this. Thanks for the hint!

**Comment by TJYSunset** [comment]
Some more explanation: without that option enabled, metadata are scanned by Android itself. Android and Google are really bad at doing anything right.

**Comment by l3u** [comment]
Wow … so my bug report should be filed at Google … and as soon as some FLOSS project does the job a multi billion dollar company messes up, everything's right?! That is indeed remarkable. Thanks for the follow-up!

**Comment by l3u** [comment]
Just fyi: I created an upstream bug report about this at Google: https://issuetracker.google.com/issues/385155398
