### ISSUE TITLE
Bigger font size (system) cuts off seconds

### ISSUE THREAD

**Issue by uli-on** [TJYSunset/Phocid#32]
I've set my font prefs system-wide in the Android prefs app (size 3 out of possible 4). With that in use (and Phocid's own font scaling set to 1.0) the last digit of the current position and of total length is not displayed in the player window, i.e. values there look like `03:2`.

Phocid v20241227, DL from GH
Android 13
Fairphone 3

**Comment by TJYSunset** [comment]
Fixed in 5aad8adaa5370edc85680a6574d74d9c78fc1249

**Comment by uli-on** [comment]
Thanks :)
