### ISSUE TITLE
Padding and autocenter the tabs

### ISSUE THREAD

**Issue by CaffeineOnIce** [TJYSunset/Phocid#4]
Will it be possible to reduce the padding between the tabs a bit so that there's no scrolling for the tabs for Songs, Playlits, etc?

Also, could the tabs be autocentered? They look very off center. 
![Screenshot_20241201_231757_Phocid](https://github.com/user-attachments/assets/a545ee41-34bb-41ea-9d42-7179b51b5be1)

**Comment by TJYSunset** [comment]
I want that feature too, too bad the great Jetpack Compost won't let me.

Instead I added an option to switch tab row types in 05abc51bd4621b525327d16e36c79179515af332.
