### ISSUE TITLE
rename white- and blacklist

### ISSUE THREAD

**Issue by secretmango** [TJYSunset/Phocid#5]
Hi there!

It might be nice to rename those to "allow-" and "blocklist"

To avoid using colors for good and bad

**Comment by TJYSunset** [comment]
At most I can rename these superficially in English string resources (but not in code). There doesn't seem to be a strong enough consensus to rename blacklist to blocklist ([Wikipedia still names the page "blacklist" without any mention of naming controversies at the time of writing](https://web.archive.org/web/20241201041819/https://en.wikipedia.org/wiki/Blacklist_(computing))), and as the current sole developer I neither natively speak English nor am Black or White, these disputes doesn't justify a whole refactor.

**Comment by TJYSunset** [comment]
Replaced in 9cc92d6e8bc07e96c92398103ae0a1b85f9895b7

**Comment by secretmango** [comment]
I think this is perfectly fine, thanks!

Wikipedia is not a neutral source. It is a community encyclopedia, and as someone with a little experience with that community, I can say there will be certain *old white men* that will resist a renaming of "blacklist" to "blocklist"
