### ISSUE TITLE
descriptive name and icon

### ISSUE THREAD

**Issue by secretmango** [TJYSunset/Phocid#7]
I am sure you have had good ideas for these.

I simply think that using an icon that has anything to do with music, and a name that is easy to read and pronounce, might gain more users.

Cheers!

**Comment by TJYSunset** [comment]
> a name that is easy to read and pronounce

The name is chosen for its similarity to Phonograph, where the UI design came from. And it's only two syllables and 6 letters. How much easier should I make it, a single letter?

Also, common names will likely get me into a trademark dispute later.

> an icon that has anything to do with music

It's literally a seal ("phocidae") wearing headphones. Yes I can't afford to hire an artist and I'm bad at graphics design.
