### ISSUE TITLE
Lag issue

### ISSUE THREAD

**Issue by Lucky390163** [TJYSunset/Phocid#8]
Almost become a perfect app, but can you look at the clip that how the app is lagging? Too much on scrolling.
Just installed the latest version 1min ago.

**Comment by TJYSunset** [comment]
Yes I know that. Mostly a Google issue, blame them for their **** framework. The current version is the best compromise I can make.

**Comment by Lucky390163** [comment]
I you have problems in maintenance you can use fossify music source code.It superbly optimized in scrolling

**Comment by TJYSunset** [comment]
They are not using Jetpack Compose as their UI framework, instead they are View-based.

**Comment by Lucky390163** [comment]
Or Auxio that's much i have - https://github.com/OxygenCobalt/Auxio.git

**Comment by Lucky390163** [comment]
Maybe the developers can help you maintain the app.Only that much i can say

**Comment by TJYSunset** [comment]
These are all View-based, the supposedly "legacy" technology. Technically I could use View components inside Compose, but I'd have to revert all the changes some day when Google decides to `@Deprecate`™ such possibility.

The best bet is to wait for Google to fix their performance problems.

**Comment by Lucky390163** [comment]
And one more small request please add recently added songs tab like this app called musicolet
![Screenshot_20241202_112801_Musicolet](https://github.com/user-attachments/assets/44b3b023-f004-41f9-9441-408217c1d71e)

**Comment by Lucky390163** [comment]
That will give this app a new functionality

**Comment by TJYSunset** [comment]
Fixed in 9a4bb292c8896a8f09c3bb7f7ef0594902a478ee

Have a build with fixes applied here (Can't publish a new version because I had to use date as version number)
[https://github.com/user-attachments/files/17994718/app-release.zi](https://github.com/user-attachments/files/17994718/app-release.zip)

**Comment by CaffeineOnIce** [comment]
On the latest build that you fixed, sorry to say, lag is still there. But yeah, it's very usable than before.

[Link to the video.](https://gofile.io/d/wzkp7s)

**Comment by TJYSunset** [comment]
Can't replicate that even in a playlist with 5000 items. Did you ran out of RAM, or by any chance your files are on an external SD card or something?

**Comment by CaffeineOnIce** [comment]
Nope. All in internal memory. Running on Samsung One UI 6.1, Android 14, Samsung S24, on Exynos, btw.

**Comment by TJYSunset** [comment]
Can you test this build that replaces all images with placeholders? I suspect the new lag is caused by image loading.
[app-release.zip](https://github.com/user-attachments/files/17995478/app-release.zip)

**Comment by CaffeineOnIce** [comment]
Can confirm. It do be the image loading that's causing the mess. It's fluid in this build. artwork loading causes the lag.

**Comment by TJYSunset** [comment]
Does this build lag? Maybe it's because the cache saturated, and I can't replicate because my 5000-item list only consists of 1000 tracks duplicated 5 times (so only 1000 images are actually loaded). I removed the caching mechanism entirely.

Ironically caching was originally meant for better performance.

[app-release.zip](https://github.com/user-attachments/files/17996187/app-release.zip)

**Comment by CaffeineOnIce** [comment]
oh yeah, it's close to perfection. Just saw a tiny lag, but it's nothing it be worried about. It's great.

**Comment by TJYSunset** [comment]
Committed as 36bdd1024deb9c35f170f3631028e201e945021e

**Comment by CaffeineOnIce** [comment]
Nope. Lag is back again. For the last 22 mins ago build. It's weird. Same lag. scrolling.

**Comment by TJYSunset** [comment]
Can you make sure the version number in about section "v20241204"? Technically this is impossible, since no related changes have been made after that.

**Comment by CaffeineOnIce** [comment]
Nevermind, I just uninstalled it again and reinstalled it. It's now fine. must have been a fluke.
